version: 0.0.1.{build}
pull_requests:
  do_not_increment_build_number: true
environment:
  COVERALLS_TOKEN:
    secure: 51s8ulHCbos7AITtIf/y5wep2T2+wTHgOapg4/DT3EHIH/AH3mqnSqVZbKCWQYjN
  NUGET_TOKEN:
    secure: Ji1yD7O5TWE6Pb9me7AJmF3FD03dKRckdjRWu/B131AebmdDQclB+D5uVkj1HH52
build_script:
- ps: .\build.ps1 -Target "Build"
test_script:
- ps: .\build.ps1 -Target "UploadCoverageReport" -coverallsToken="$ENV:COVERALLS_TOKEN"
artifacts:
- path: src/bin/**/Hippocampus.SQL.dll
  name: build-dll
- path: src/bin/**/Hippocampus.SQL.xml
  name: build-xml
- path: src/bin/**/Hippocampus.SQL.pdb
  name: build-pdb
deploy_script:
- ps: .\build.ps1 -Target "Deploy"
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false